diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "joint_left_wheel"
  right_wheel: "joint_right_wheel"
  publish_rate: 50.0
  wheel_separation: 0.2  # Adjust based on your robot dimensions
  wheel_radius: 0.055     # Adjust based on your wheel size
  cmd_vel_timeout: 0.5
  enable_odom_tf: true
  odom_frame_id: "odom"
  base_frame_id: "base_footprint"
  cmd_vel_topic: "/cmd_vel" 
  odom_topic: "/odom"
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.001]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.0, 0.0, 0.001]

  # Joint limits
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 2.5
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 1.0
      has_acceleration_limits: true
      max_acceleration: 2.5

gazebo_ros_control:
  pid_gains:
    joint_right_wheel: {p: 0.7, i: 0.0, d: 0.0}
    joint_left_wheel: {p: 0.5, i: 0.0, d: 0.0}