obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.15, 0.12], [0.15, -0.12],[-0.15, 0.12], [-0.15, -0.12]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: camera_link, data_type: PointCloud2, topic: /point_cloud_data, marking: true, clearing: true}